parameters:
  artifactName: ''

steps:
- task: DownloadPipelineArtifact@0
  displayName: 'Download {{ parameters.artifactName }}'
  inputs:
    artifactName: ${{ parameters.artifactName }}
    targetPath: artifacts