steps:
- task: PowerShell@2
  displayName: List PR Changed Files
  inputs:
    targetType: inline
    pwsh: true
    script: |
      $targetBranch = $(System.PullRequest.TargetBranch)
      git fetch --no-tags origin "${targetBranch}:origin/base"
      $changedFiles = git --no-pager diff --name-only --diff-filter=ACMRT origin/base -- .
      Write-Host "Total updated files:" $changedFiles.Count
      Write-Host "All Updated files:"
      $changedFiles | Foreach-Object {Write-Host $_}
      $RepoArtifacts = 'artifacts'
      if(-not (Test-Path $RepoArtifacts)){
        New-Item -ItemType Directory -Name $RepoArtifacts
      }
      $changedFiles | Out-File $RepoArtifacts/FilesChanged.txt
