steps:
- task: PowerShell@2
  displayName: List PR Changed Files
  inputs:
    targetType: inline
    pwsh: true
    script: |
      # refer to https://learn.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables-devops-services
      # get the target branch name
      $targetBranch = $(System.PullRequest.TargetBranch)
      # fetch the targetBranch from origin to local branch and rename the branch to 'origin/base'
      git fetch --no-tags origin "${targetBranch}:origin/base"
      # refer to https://git-scm.com/docs/git-diff
      # compare the pr and targetBranch branch, get the changed file list
      # diff-filter options are ACMRT, which are: Added, Copied, Modified, Renamed , Changed
      $changedFiles = git --no-pager diff --name-only --diff-filter=ACMRT origin/base -- .
      Write-Host "Total updated files:" $changedFiles.Count
      Write-Host "All Updated files:"
      $changedFiles | Foreach-Object {Write-Host $_}
      $RepoArtifacts = 'artifacts'
      if(-not (Test-Path $RepoArtifacts)){
        New-Item -ItemType Directory -Name $RepoArtifacts
      }
      $changedFiles | Out-File $RepoArtifacts/FilesChanged.txt
