steps:
- task: AzurePowerShell@5
  inputs:
    pwsh: true
    azureSubscription: '$(AzureSubscription)'
    ScriptType: 'InlineScript'
    Inline: |
      $GithubToken = Get-AzKeyVaultSecret -VaultName $(GithubPATKeyVaultName) -Name $(GithubPATKeyVaultAccount) -AsPlainText
      Write-Host "##vso[task.setvariable variable=GithubToken;issecret=true]$GithubToken"
    azurePowerShellVersion: 'LatestVersion'
  displayName: Get Github PAT from Key Vault
