parameters:
- name: serviceConnectionName
  type: string
- name: keyVaultName
  type: string
- name: secretName
  type: string
- name: outVar
  type: string
  default: 'KVSecret'
- name: execCondition
  type: string
  default: succeeded()

steps:
- task: AzurePowerShell@5
  displayName: Get Secret from Azure KeyVault
  condition: ${{ parameters.execCondition }}
  inputs:
    azurePowerShellVersion: LatestVersion
    azureSubscription: ${{ parameters.serviceConnectionName }}
    pwsh: true
    scriptType: InlineScript
    inline: |
      $secretValue = Get-AzKeyVaultSecret -VaultName ${{ parameters.keyVaultName }} -Name ${{ parameters.secretName }} -AsPlainText
      Write-Host "##vso[task.setvariable variable=${{ parameters.outVar }};issecret=true;isreadonly=true]$secretValue"
