parameters:
- name: name
  type: string
- name: vmImage
  type: string
- name: osType
  type: string
- name: psVersion
  type: string
- name: dotnetVersion
  type: string
- name: galleryName
  type: string
- name: pipelineBuildId
  type: string

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 600
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: UseDotNet@2
    displayName: Install desired .NET version ${{ parameters.dotnetVersion }}
    condition: ne('${{ parameters.dotnetVersion }}', '')
    inputs:
      packageType: sdk
      version: ${{ parameters.dotnetVersion }}

  - task: PowerShell@2
    displayName: Install desired Powershell version ${{ parameters.psVersion }}
    condition: ne('${{ parameters.psVersion }}', '')
    inputs:
      pwsh: true
      targetType: filePath
      filePath: ./tools/TestFx/Live/InitializeLiveTestEnvironment.ps1
      arguments: -DesiredVersion ${{ parameters.psVersion }}

  - task: PowerShell@2
    displayName: Prepare for artifacts
    inputs:
      pwsh: true
      targetType: inline
      script:
        New-Item -Name $(ArtifactsName) -Path $(Pipeline.Workspace) -ItemType Directory -Force

  - task: PowerShell@2
    displayName: Prepare for dump capture
    inputs:
      pwsh: true
      targetType: inline
      script: |
        reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpFolder /t REG_EXPAND_SZ /d "$(DataLocation)" /f
        reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpCount /t REG_DWORD /d 10 /f
        reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpType /t REG_DWORD /d 2 /f

  - task: PowerShell@2
    displayName: Install desired Az module from ${{ parameters.galleryName }}
    inputs:
      pwsh: true
      targetType: filePath
      filePath: ./tools/TestFx/Live/InvokeLiveTestCITask.ps1
      arguments: -UseWindowsPowerShell ('${{ parameters.psVersion }}' -eq '5.1') -ScriptFile './tools/TestFx/Live/InstallLiveTestAzModules.ps1 -Source ${{ parameters.galleryName }} -AzPackagesLocation (Join-Path -Path $(DataLocation) -ChildPath AzPreviewPackages)'

  - template: get-keyvault-secret-steps.yml
    parameters:
      serviceConnectionName: $(LiveTestServiceConnectionName)
      keyVaultName: $(LiveTestServicePrincipalKeyVaultName)
      secretName: $(LiveTestServicePrincipalSecretName)
      outVar: 'LiveTestServicePrincipalSecret'
      execCondition: and(succeeded(), ne(variables['skipLatest'], 'true'))

  - task: PowerShell@2
    displayName: Get temp PS1
    condition: always()
    inputs:
      pwsh: true
      targetType: inline
      script: |
        Copy-Item -Path $(Agent.TempDirectory)/* -Destination $(DataLocation) -Force

  - task: PublishPipelineArtifact@1
    displayName: Publish live test results to pipeline artifact
    condition: always()
    inputs:
      artifact: livetest-os-${{ parameters.vmImage }}-ps-${{ replace(parameters.psVersion, '*', 'x') }}
      targetPath: $(DataLocation)
