parameters:
  name: ''
  psVersion: ''
  agentPoolName: ''
  agentPoolVMImage: ''
  netCoreVersion: ''
  PowerShellPath: '$(Build.SourcesDirectory)/ps_preview'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 180
  pool:
    name: ${{ parameters.agentPoolName }}
    vmImage: ${{ parameters.agentPoolVMImage }}

  steps:
  - task: UseDotNet@2
    condition: ne(variables['netCoreVersion'], '')
    displayName: 'Prepare .NET Core ${{ parameters.netCoreVersion }}'
    inputs:
      packageType: sdk
      version: ${{ parameters.netCoreVersion }}

  - task: PowerShell@2
    condition: and(succeeded(), eq('${{ parameters.psVersion }}', 'preview'))
    displayName: DownLoad Package for ${{ parameters.psVersion }}
    inputs:
      filePath: 'tools/Test/SmokeTest/DownLoadPowershellPreviewPackage.ps1'
      arguments: '-DowanloadDir $(Build.SourcesDirectory) -AgentOS "$(Agent.OS)" -AgentAarchitecture "$(Agent.OSArchitecture)"'

  - task: ExtractFiles@1
    condition: and(succeeded(), eq('${{ parameters.psVersion }}', 'preview'))
    displayName: 'Extract PowerShell Preview Package '
    inputs:
      archiveFilePatterns: |
        *.zip
        *.tar.gz
      destinationFolder: ${{ parameters.PowerShellPath }}
      overwriteExistingFiles: true

  - task: PowerShell@2
    displayName: Prepare Powershell ${{ parameters.psVersion }}
    inputs:
      filePath: 'tools/Test/SmokeTest/PrepareRequiredPowershell.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: DownloadPipelineArtifact@2
    condition: and(succeeded(), eq(variables['GalleryName'], 'LocalRepo'), eq(variables['PipelineId'], ''))
    displayName: Download Latest Artifacts from Build Pipeline
    inputs:
      buildType: specific
      project: $(ProjectToDownloadArtifacts)
      definition: $(BuildPipelineName)
      buildVersionToDownload: 'latest'
      artifactName: $(ArtifactName)
      targetPath: $(Pipeline.Workspace)

  - task: DownloadPipelineArtifact@2
    condition: and(succeeded(), eq(variables['GalleryName'], 'LocalRepo'), ne(variables['PipelineId'], ''))
    displayName: Download Specified Artifacts from Build Pipeline
    inputs:
      buildType: 'specific'
      project: $(ProjectToDownloadArtifacts)
      definition: $(BuildPipelineName)
      buildVersionToDownload: 'specific'
      pipelineId: $(PipelineId)
      artifactName: '$(ArtifactName)'
      targetPath: '$(Pipeline.Workspace)'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['GalleryName'], 'LocalRepo'))
    displayName: Copy Artifacts to LocalRepo
    inputs:
      targetType: 'inline'
      script: |
       New-Item -Path "$(Pipeline.Workspace)" -Name "LocalRepo" -ItemType "directory"
       Copy-Item -Path "$(Pipeline.Workspace)\\*.nupkg" -Destination "$(Pipeline.Workspace)\\LocalRepo\\"
       Write-Host "List artifacts..."
       Get-ChildItem "$(Pipeline.Workspace)\\LocalRepo\\"

  - task: NuGetCommand@2
    condition: and(succeeded(), eq(variables['GalleryName'], 'LocalRepo'))
    displayName: 'Download Previous Az .nupkg Files'
    inputs:
      command: custom
      arguments: 'install Az -directdownload -packagesavemode nupkg -source https://www.powershellgallery.com/api/v2 -OutputDirectory packages'

  - task: NuGetCommand@2
    condition: and(succeeded(), eq(variables['GalleryName'], 'LocalRepo'))
    displayName: 'Download Previous Az.Compute .nupkg Files'
    inputs:
      command: custom
      arguments: 'install Az.Compute -directdownload -packagesavemode nupkg -source https://www.powershellgallery.com/api/v2 -OutputDirectory packages'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['GalleryName'], 'LocalRepo'))
    displayName: 'Copy Previous Release .nupkg files to LocalRepo'
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem $(System.DefaultWorkingDirectory)/packages -Recurse -Include *.nupkg | Copy-Item -Destination "$(Pipeline.Workspace)\\LocalRepo\\" -Force
        Write-Host "List localRepo..."
        Get-ChildItem "$(Pipeline.Workspace)\\LocalRepo\\"

  - task: PowerShell@2
    displayName: Install Az Modules from $(GalleryName)
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/InstallAzModules.ps1 -Gallery $(GalleryName) -LocalRepoLocation $(LocalRepoLocation)" -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - template: get-keyvault-secret-steps.yml
    parameters:
      serviceConnectionName: $(ServiceConnectionName)
      keyVaultName: $(ServicePrincipalKeyVaultName)
      secretName: $(ServicePrincipalSecretName)
      outVar: 'ServicePrincipalSecret'

  - task: PowerShell@2
    displayName: Connect AzAccount
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/ConnectAzAccount.ps1 $(ServicePrincipalSecret) $(ServicePrincipal) $(TenantId) $(SubscriptionId) " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Run Smoke Test
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/RmCoreSmokeTests.ps1 " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'
      failOnStderr: true

  - task: PowerShell@2
    displayName: 'Run Smoke Test Reversely'
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/RmCoreSmokeTests.ps1 -Reverse" -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'
      failOnStderr: true

  - task: PowerShell@2
    displayName: Clean Az Modules
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/CleanAzModules.ps1" -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Update Az Modules
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/UpdateAzModules.ps1 -Gallery $(GalleryName) -AllowEquality $(AllowEquality) " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Run Smoke Test
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/RmCoreSmokeTests.ps1 " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'
      failOnStderr: true

  - task: PowerShell@2
    displayName: 'Run Smoke Test Reversely'
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/RmCoreSmokeTests.ps1 -Reverse " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'
      failOnStderr: true

  - task: PowerShell@2
    displayName: Clean Az Modules
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/CleanAzModules.ps1" -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Install an individual module
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/InstallAnIndividualModule.ps1 -Gallery $(GalleryName) " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Clean Az Modules
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/CleanAzModules.ps1" -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Update an individual module
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/UpdateAnIndividualModule.ps1 -Gallery $(GalleryName) -AllowEquality $(AllowEquality) " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Clean Az Modules
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/CleanAzModules.ps1" -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Install Az on top of an individual module
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/InstallAzOnTopOfAnIndividualModule.ps1 -Gallery $(GalleryName) -AllowEquality $(AllowEquality) " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Clean Az Modules
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/CleanAzModules.ps1" -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'

  - task: PowerShell@2
    displayName: Install an individual module on top of Az
    inputs:
      filePath: 'tools/Test/SmokeTest/ScriptsCaller.ps1'
      arguments: '-RequiredPsVersion ${{ parameters.psVersion }} -Script "./tools/Test/SmokeTest/InstallAnIndividualModuleOnTopOfAz.ps1 -Gallery $(GalleryName) -AllowEquality $(AllowEquality) " -PowerShellPath "${{ parameters.PowerShellPath }}" -AgentOS "$(Agent.OS)"'
