# Variable 'BaseBranch' was defined in the Variables tab
# Variable 'ServiceName' was defined in the Variables tab
# Multi-job configuration must be converted to matrix strategy: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-job-configuration
resources:
  repositories:
  - repository: self
    type: git
    ref: main

pr:
  branches:
    include:
      - main
  paths:
    include:
      - .azure-pipeline
      - tools
      - src/lib

jobs:
- job: Job_1
  displayName: 'Sync to ${{ parameters.BranchName }}'
  timeoutInMinutes: 90
  pool:
    name: Hosted VS2017
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Config git
    inputs:
      targetType: inline
      script: >-
        git config --global user.email "azurepowershell@ms.com"

        git config --global user.name "azurepowershell"

        git checkout ${{ parameters.BranchName }}
      pwsh: true
  - task: PowerShell@2
    displayName: Sync .azure-pipelines folder from main to ${{ parameters.BranchName }}
    inputs:
      targetType: inline
      script: >-
        #cp .azure-pipelines .azure-pipelines-tmp -r

        rm .azure-pipelines -r

        mv .azure-pipelines-tmp .azure-pipelines

        git add .azure-pipelines
      pwsh: true
  - task: PowerShell@2
    displayName: Sync src/lib folder from main to ${{ parameters.BranchName }}
    inputs:
      targetType: inline
      script: >-
        #cp src/lib src/lib-tmp -r

        rm src/lib -r

        mv src/lib-tmp src/lib

        git add src/lib
      pwsh: true
  - task: PowerShell@2
    displayName: Sync tools folder from main to ${{ parameters.BranchName }}
    inputs:
      targetType: inline
      script: >-
        #cp tools tools-tmp -r

        rm tools -r

        mv tools-tmp tools

        git add tools

        git commit -m "Sync tools folder from main branch to ${{ parameters.BranchName }} branch"

        git remote set-url origin https://$env:GITHUB_TOKEN@github.com/Azure/azure-powershell.git

        git push origin syncToolsFolder --force
      pwsh: true
...
