id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Close stale issues
      frequencies:
      - daily:
          time: 1:0
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: needs-author-feedback
      - hasLabel:
          label: no-recent-activity
      - noActivitySince:
          days: 14
      actions:
      - closeIssue
    - description: Add no recent activity label to issues
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: needs-author-feedback
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: Hi, we're sending this friendly reminder because we haven't heard back from you in a while. We need more information about this issue to help address it. Please be sure to give us your input within the next **7 days**. If we don't hear back from you within **14 days** of this comment the issue will be automatically closed. Thank you!
    - description: '[Resolve Workflow] Close Addressed Issues'
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: issue-addressed
      - noActivitySince:
          days: 7
      actions:
      - addReply:
          reply: Hi @${issueAuthor}, since you haven't asked that we "`/unresolve`" the issue, we'll close this out. If you believe further discussion is needed, please add a comment "`/unresolve`" to reopen the issue.
      - closeIssue
    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: needs-author-feedback
      - isOpen
      then:
      - addLabel:
          label: needs-team-attention
      - removeLabel:
          label: needs-author-feedback
      description: Replace needs author feedback label with needs attention label when the author comments on an issue
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: Remove no recent activity label from issues
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: Remove no recent activity label when an issue is commented on
    - if:
      - payloadType: Issues
      - isAction:
          action: Labeled
      - hasLabel:
          label: needs-triage
      - not:
          labelAdded:
            label: needs-triage
      then:
      - removeLabel:
          label: needs-triage
      description: Remove needs-triage label on issues once they are labeled
    - if:
      - or:
        - payloadType: Issues
      - isAction:
          action: Labeled
      then: []
      description: Triage issues to the service team
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - and:
        - not:
            activitySenderHasPermission:
              permission: Write
        - not:
            activitySenderHasAssociation:
              association: Member
        - not:
            activitySenderHasAssociation:
              association: Collaborator
        - not:
            activitySenderHasPermission:
              permission: Admin
      - not:
          hasLabel:
            label: customer-reported
      then:
      - addLabel:
          label: customer-reported
      - addReply:
          reply: Thank you for your contribution ${issueAuthor}! We will review the pull request and get back to you soon.
      description: Add customer-reported label to PRs from customers
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - and:
        - not:
            activitySenderHasPermission:
              permission: Write
        - not:
            activitySenderHasAssociation:
              association: Member
        - not:
            activitySenderHasAssociation:
              association: Collaborator
        - not:
            activitySenderHasPermission:
              permission: Admin
      - not:
          hasLabel:
            label: customer-reported
      then:
      - addLabel:
          label: customer-reported
      - addLabel:
          label: needs-triage
      description: Add customer-reported label to issues coming from non-collaborators
      triggerOnOwnActions: true
    - if:
      - payloadType: Issues
      - labelAdded:
          label: issue-addressed
      then:
      - addReply:
          reply: Hi @${issueAuthor}.  Thank you for opening this issue and giving us the opportunity to assist.  We believe that this has been addressed.  If you feel that further discussion is needed, please add a comment with the text “`/unresolve`” to remove the “issue-addressed” label and continue the conversation.
      - removeLabel:
          label: needs-triage
      - removeLabel:
          label: needs-team-triage
      - removeLabel:
          label: needs-team-attention
      - removeLabel:
          label: needs-author-feedback
      - removeLabel:
          label: no-recent-activity
      description: '[Resolve Workflow] Issue Addressed Label Applied'
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: issue-addressed
      - commentContains:
          pattern: /unresolve
          isRegex: False
      - or:
        - isActivitySender:
            issueAuthor: True
        - activitySenderHasPermission:
            permission: Admin
        - activitySenderHasPermission:
            permission: Write
      then:
      - reopenIssue
      - removeLabel:
          label: issue-addressed
      - addLabel:
          label: needs-team-attention
      description: '[Resolve Workflow] Unresolve Command by Author'
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: issue-addressed
      - commentContains:
          pattern: /unresolve
          isRegex: False
      - and:
        - isActivitySender:
            issueAuthor: True
        - activitySenderHasPermission:
            permission: Admin
        - activitySenderHasPermission:
            permission: Write
      then:
      - addReply:
          reply: Hi ${contextualAuthor}, only the original author of the issue can ask that it be unresolved.  Please open a new issue with your scenario and details if you would like to discuss this topic with the team.
      description: '[Resolve Workflow] Unresolve Command Without Permissions'
onFailure:
onSuccess:
