options:
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    emitter-output-dir: "{output-dir}/{service-dir}/Resources/Policy.Autorest"
    clear-output-folder: true
    debug: true
    azure: true
    module-version: 0.1.0
    prefix: "Az"
    subject-prefix: "Policy"
    service-name: Policy
    module-name: "{prefix}.{service-name}"
    root-module-name: Az.Resources
    output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    disable-transform-identity-type-for-operation:
      - PolicyAssignments_Update
    resourcegroup-append: false
    identity-correction-for-post: false
    export-properties-for-dict: false
    nested-object-to-string: false
    metadata:
      scriptsToProcess:
      - ./custom/Helpers.ps1
    directive:
      # Hide the Operations endpoint from public interface
      - where:
          subject: Operation
        hide: true
      # Default SubscriptionId to current context
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: "(Get-AzContext).Subscription.Id"
      # Remove unexpanded parameter sets for Create/Update
      - where:
          variant: ^(Create|Update|Export)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      # Remove ViaIdentity Create variants
      - where:
          variant: ^CreateViaIdentity$|^CreateViaIdentityExpanded$
        remove: true
      # Remove Set variants
      - where:
          verb: Set
        remove: true
      # Remove ManagementGroupInputObject parameter for all cmdlets, since it's not supported
      - where:
          variant: ^(Get|Delete|Update)ViaIdentityManagementGroup(Expanded)?$
        remove: true
      # Hide separate cmdlets generated for tenant-level GETs. These are used by Get-AzPolicy*
      # customization to match behavior of current SDK cmdlets.
      - where:
          subject: .*Built
        hide: true
      # Create aliases of Set-*, since they are not supported/generated by autorest.powershell
      # They are provide in the new policy module for compatibility with current SDK module.
      # Since neither definitions nor set definitions generate Update-* cmdlets, both
      # Set-* and Update-* cmdlets are implemented by wrapping the generated New-* cmdlets.
      - where:
          verb: Update
          subject: PolicyAssignment
        set:
          alias:
            Set-AzPolicyAssignment
      - where:
          verb: Update
          subject: PolicyExemption
        set:
          alias:
            Set-AzPolicyExemption
      # Rename generated hashtable parameters to avoid type mismatch, since generated code
      # uses hashtable and previous SDK cmdlets use [JSON] string. Note, removing any
      # of these will cause builds to fail, since a parameter is not allowed to be
      # multiple types.
      - where:
          parameter-name: Parameter
        set:
          parameter-name: ParameterTable
      # Rename this parameter name to the one used by all the other resource types
      - where:
          parameter-name: ManagementGroupName
          subject: PolicyDefinitionVersion|PolicySetDefinitionVersion
        set:
          parameter-name: ManagementGroupId
      # Formatting directives
      - where:
          model-name: PolicyAssignment
        set:
          format-table:
            properties:
              - Name
              - Scope
              - EnforcementMode
              - DisplayName
      - where:
          model-name: PolicyDefinition
        set:
          format-table:
            properties:
              - Name
              - PolicyType
              - DisplayName
      - where:
          model-name: PolicyExemption
        set:
          format-table:
            properties:
              - Name
              - PolicyAssignmentId
              - DisplayName
      - where:
          model-name: PolicySetDefinition
        set:
          format-table:
            properties:
              - Name
              - PolicyType
              - DisplayName
      # Hide parameters that aren't supported.
      - where:
          verb: Get
          parameter-name: Top
        hide: true
      # Remove or hide cmdlets that are customized or not supported at all
      - where:
          verb: New|Get|Remove|Update
        hide: true
      - where:
          verb: Get|New|Remove|Update
          subject: PolicyDefinitionVersion|PolicySetDefinitionVersion
        hide: true