blank_issues_enabled: false
contact_links:
  - name: General PowerShell Question
    url: https://github.com/PowerShell/PowerShell/issues/
    about: PowerShell module or language related question
  - name: Microsoft Graph Module Question
    url: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/
    about: Question about Microsoft Graph PowerShell Module 
  - name: AutoRest PowerShell Generator Question
    url: https://github.com/Azure/autorest.powershell/issues
    about: Question about PowerShell plugin of AutoRest
