# Variable used in testing.
$ENV:ResourceGroupName = 'powershell-sdk-testing'
$ENV:Location = 'westcentralus'
$ENV:LabPlanName = 'labplan-unit-powershell'
$ENV:LabName = 'lab-unit-powershell'
$ENV:NewLabName = 'new-lab-unit-powershell'
$ENV:LabPlanNameToDelete = 'labplan-unit-powershell-del'
$ENV:LabNameToDelete = 'lab-unit-powershell-del'
$ENV:LabNameLike = '*powershell'
$ENV:UserEmail = 'test@contosouniversity.com'
$ENV:UserName = 'testuser'
$ENV:UserEmailSecond = 'testsecond@contosouniversity.com'
$ENV:UserNameSecond = 'testseconduser'
$ENV:ScheduleName = 'testschedule'
$ENV:ScheduleNameSecond = 'secondtestschedule'
$ENV:SIGName = 'sigunitpowershell'
$ENV:SubscriptionId = '63d7e191-c910-43ba-908f-252519936998'