FROM mcr.microsoft.com/powershell:ubuntu-18.04

ARG ARTIFACTS=/tmp/artifacts/
ARG ARTIFACT=*.nupkg
ARG TEMPREPO=tmp
ARG MODULE=Az
ARG CONFIG=config
ARG AZURERM_CONTEXT_SETTINGS=AzureRmContextSettings.json
ARG AZURE=/root/.Azure
ARG VCS_REF="none"
ARG Build_Date=
ARG VERSION=
ARG IMAGE_NAME=mcr.microsoft.com/azure-powershell:${VERSION}-ubuntu-18.04

ENV AZUREPS_HOST_ENVIRONMENT="dockerImage/${VERSION}-ubuntu-18.04"

LABEL maintainer="Azure PowerShell Team <azdevxps@microsoft.com>" \
      readme.md="http://aka.ms/azpsdockerreadme" \
      description="This Dockerfile will install the latest release of Azure PowerShell." \
      org.label-schema.build-date=${Build_Date} \
      org.label-schema.usage="http://aka.ms/azpsdocker" \
      org.label-schema.url="http://aka.ms/azpsdockerreadme" \
      org.label-schema.vcs-url="https://github.com/Azure/azure-powershell" \
      org.label-schema.name="azure powershell" \
      org.label-schema.vendor="Azure PowerShell" \
      org.label-schema.version=${VERSION} \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vcs-ref=${VCS_REF} \
      org.label-schema.docker.cmd="docker run --rm ${IMAGE_NAME} pwsh -c '\$PSVERSIONTABLE'" \
      org.label-schema.docker.cmd.devel="docker run -it --rm -e 'DebugPreference=Continue' ${IMAGE_NAME} pwsh" \
      org.label-schema.docker.cmd.test="currently not available" \
      org.label-schema.docker.cmd.help="docker run --rm ${IMAGE_NAME} pwsh -c Get-Help"

# install azure-powershell from built artifacts
COPY ${ARTIFACT} ${ARTIFACTS}
RUN pwsh -Command Register-PSRepository -Name ${TEMPREPO} -SourceLocation ${ARTIFACTS} -PublishLocation $ARTIFACTS -InstallationPolicy Trusted -PackageManagementProvider NuGet && \
    pwsh -Command Install-Module -Name ${MODULE} -Repository ${TEMPREPO} && \
    pwsh -Command Get-Module -ListAvailable && \
    pwsh -Command Unregister-PSRepository -Name ${TEMPREPO} && \
    pwsh -Command Remove-Item ${ARTIFACTS} -Recurse

# create AzureRmContextSettings.json before it was generated
COPY ${CONFIG}/${AZURERM_CONTEXT_SETTINGS} ${AZURE}/${AZURERM_CONTEXT_SETTINGS}

CMD [ "pwsh" ]