# Variable used in testing.
$ENV:ResourceGroupName = 'rg-test-powershell'
$ENV:Location = 'eastus2'
$ENV:LabPlanName = 'labplan-unit-powershell'
$ENV:LabName = 'lab-unit-powershell'
$ENV:NewLabName = 'new-lab-unit-powershell'
$ENV:LabPlanNameToDelete = 'labplan-unit-powershell-del'
$ENV:LabNameToDelete = 'lab-unit-powershell-del'
$ENV:LabNameLike = '*powershell'
$ENV:UserEmail = 'test@contosouniversity.com'
$ENV:UserName = 'testuser'
$ENV:UserEmailSecond = 'testsecond@contosouniversity.com'
$ENV:UserNameSecond = 'testseconduser'
$ENV:ScheduleName = 'testschedule'
$ENV:ScheduleNameSecond = 'secondtestschedule'
$ENV:SIGName = 'sigunitpowershell'
$ENV:SubscriptionId = '2d5eedc9-8509-41fe-aac8-f16d54583ac6'