
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
API for updating inventory metadata and inventory configuration
.Description
API for updating inventory metadata and inventory configuration
.Example
{{ Add code here }}
.Example
{{ Add code here }}

.Inputs
Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Models.Api20201201Preview.IManageInventoryMetadataRequest
.Inputs
Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Models.IEdgeOrderPartnerApiSIdentity
.Outputs
System.Boolean
.Notes
COMPLEX PARAMETER PROPERTIES

To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.

INPUTOBJECT <IEdgeOrderPartnerApiSIdentity>: Identity Parameter
  [FamilyIdentifier <String>]: Unique identifier for the product family
  [Id <String>]: Resource identity path
  [Location <String>]: The location of the resource
  [SerialNumber <String>]: The serial number of the device
  [SubscriptionId <String>]: The ID of the target subscription.

MANAGEINVENTORYMETADATAREQUEST <IManageInventoryMetadataRequest>: Request body for ManageInventoryMetadata call
  InventoryMetadata <String>: Inventory metadata to be updated
  [ConfigurationOnDeviceConfigurationIdentifier <String>]: Configuration identifier on device
.Link
https://docs.microsoft.com/en-us/powershell/module/az.edgeorderpartnerapis/invoke-azedgeorderpartnerapismanageinventorymetadata
#>
function Invoke-AzEdgeOrderPartnerApiSManageInventoryMetadata {
[OutputType([System.Boolean])]
[CmdletBinding(DefaultParameterSetName='ManageExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(ParameterSetName='Manage', Mandatory)]
    [Parameter(ParameterSetName='ManageExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Path')]
    [System.String]
    # Unique identifier for the product family
    ${FamilyIdentifier},

    [Parameter(ParameterSetName='Manage', Mandatory)]
    [Parameter(ParameterSetName='ManageExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Path')]
    [System.String]
    # The location of the resource
    ${Location},

    [Parameter(ParameterSetName='Manage', Mandatory)]
    [Parameter(ParameterSetName='ManageExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Path')]
    [System.String]
    # The serial number of the device
    ${SerialNumber},

    [Parameter(ParameterSetName='Manage')]
    [Parameter(ParameterSetName='ManageExpanded')]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Runtime.DefaultInfo(Script='(Get-AzContext).Subscription.Id')]
    [System.String]
    # The ID of the target subscription.
    ${SubscriptionId},

    [Parameter(ParameterSetName='ManageViaIdentity', Mandatory, ValueFromPipeline)]
    [Parameter(ParameterSetName='ManageViaIdentityExpanded', Mandatory, ValueFromPipeline)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Models.IEdgeOrderPartnerApiSIdentity]
    # Identity Parameter
    # To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    ${InputObject},

    [Parameter(ParameterSetName='Manage', Mandatory, ValueFromPipeline)]
    [Parameter(ParameterSetName='ManageViaIdentity', Mandatory, ValueFromPipeline)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Models.Api20201201Preview.IManageInventoryMetadataRequest]
    # Request body for ManageInventoryMetadata call
    # To construct, see NOTES section for MANAGEINVENTORYMETADATAREQUEST properties and create a hash table.
    ${ManageInventoryMetadataRequest},

    [Parameter(ParameterSetName='ManageExpanded', Mandatory)]
    [Parameter(ParameterSetName='ManageViaIdentityExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Body')]
    [System.String]
    # Inventory metadata to be updated
    ${InventoryMetadata},

    [Parameter(ParameterSetName='ManageExpanded')]
    [Parameter(ParameterSetName='ManageViaIdentityExpanded')]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Body')]
    [System.String]
    # Configuration identifier on device
    ${ConfigurationOnDeviceConfigurationIdentifier},

    [Parameter()]
    [Alias('AzureRMContext', 'AzureCredential')]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Azure')]
    [System.Management.Automation.PSObject]
    # The credentials, account, tenant, and subscription used for communication with Azure.
    ${DefaultProfile},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Run the command as a job
    ${AsJob},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Run the command asynchronously
    ${NoWait},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Returns true when the command succeeds
    ${PassThru},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName

        if ($null -eq [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PowerShellVersion) {
            [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PowerShellVersion = $Host.Runspace.Version.ToString()
        }         
        $preTelemetryId = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId
        if ($preTelemetryId -eq '') {
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId =(New-Guid).ToString()
            [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.module]::Instance.Telemetry.Invoke('Create', $MyInvocation, $parameterSet, $PSCmdlet)
        } else {
            $internalCalledCmdlets = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets
            if ($internalCalledCmdlets -eq '') {
                [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets = $MyInvocation.MyCommand.Name
            } else {
                [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets += ',' + $MyInvocation.MyCommand.Name
            }
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = 'internal'
        }

        $mapping = @{
            Manage = 'Az.EdgeOrderPartnerApiS.private\Invoke-AzEdgeOrderPartnerApiSManageInventoryMetadata_Manage';
            ManageExpanded = 'Az.EdgeOrderPartnerApiS.private\Invoke-AzEdgeOrderPartnerApiSManageInventoryMetadata_ManageExpanded';
            ManageViaIdentity = 'Az.EdgeOrderPartnerApiS.private\Invoke-AzEdgeOrderPartnerApiSManageInventoryMetadata_ManageViaIdentity';
            ManageViaIdentityExpanded = 'Az.EdgeOrderPartnerApiS.private\Invoke-AzEdgeOrderPartnerApiSManageInventoryMetadata_ManageViaIdentityExpanded';
        }
        if (('Manage', 'ManageExpanded') -contains $parameterSet -and -not $PSBoundParameters.ContainsKey('SubscriptionId')) {
            $PSBoundParameters['SubscriptionId'] = (Get-AzContext).Subscription.Id
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }

    finally {
        $backupTelemetryId = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId
        $backupInternalCalledCmdlets = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
    }

}
end {
    try {
        $steppablePipeline.End()

        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = $backupTelemetryId
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets = $backupInternalCalledCmdlets
        if ($preTelemetryId -eq '') {
            [Microsoft.Azure.PowerShell.Cmdlets.EdgeOrderPartnerApiS.module]::Instance.Telemetry.Invoke('Send', $MyInvocation, $parameterSet, $PSCmdlet)
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        }
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = $preTelemetryId

    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }
} 
}
