
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ThresholdRuleV2.
.Description
Create an in-memory object for ThresholdRuleV2.

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.CloudHealth.Models.ThresholdRuleV2
.Link
https://learn.microsoft.com/powershell/module/Az.CloudHealth/new-azmonitorhealthmodelthresholdrulev2object
#>
function New-AzMonitorHealthModelThresholdRuleV2Object {
    [Microsoft.Azure.PowerShell.Cmdlets.CloudHealth.ModelCmdletAttribute()]
    [OutputType('Microsoft.Azure.PowerShell.Cmdlets.CloudHealth.Models.ThresholdRuleV2')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(HelpMessage="ISO 8601 duration for the historical look-back window used by dynamic threshold computation. Only applicable when operator is Dynamic.")]
        [Microsoft.Azure.PowerShell.Cmdlets.CloudHealth.PSArgumentCompleterAttribute("PT5M", "PT15M", "PT30M", "PT1H")]
        [string]
        $LookBackWindow,
        [Parameter(Mandatory, HelpMessage="Operator how to compare the signal value with the threshold.")]
        [Microsoft.Azure.PowerShell.Cmdlets.CloudHealth.PSArgumentCompleterAttribute("GreaterThan", "LessThan", "LessThanOrEqual", "GreaterThanOrEqual", "Equal", "NotEqual", "Dynamic")]
        [string]
        $Operator,
        [Parameter(HelpMessage="Sensitivity level for dynamic threshold detection. Only applicable when operator is Dynamic.")]
        [Microsoft.Azure.PowerShell.Cmdlets.CloudHealth.PSArgumentCompleterAttribute("Low", "Medium", "High")]
        [string]
        $Sensitivity,
        [Parameter(HelpMessage="Threshold value.")]
        [double]
        $Threshold
    )

    process {
        $Object = [Microsoft.Azure.PowerShell.Cmdlets.CloudHealth.Models.ThresholdRuleV2]::New()

        if ($PSBoundParameters.ContainsKey('LookBackWindow')) {
            $Object.LookBackWindow = $LookBackWindow
        }
        if ($PSBoundParameters.ContainsKey('Operator')) {
            $Object.Operator = $Operator
        }
        if ($PSBoundParameters.ContainsKey('Sensitivity')) {
            $Object.Sensitivity = $Sensitivity
        }
        if ($PSBoundParameters.ContainsKey('Threshold')) {
            $Object.Threshold = $Threshold
        }
        return $Object
    }
}

