// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

namespace Microsoft.Azure.PowerShell.Cmdlets.ChangeSafety.Cmdlets
{
    using System.Net.Http;
    using System.Threading.Tasks;
    using Microsoft.Azure.PowerShell.Cmdlets.ChangeSafety.Models;

    // region Get
    public partial class GetAzChangeSafetyChangeRecord_Get { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyChangeRecord_Get1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyChangeRecord_GetViaIdentity1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyChangeRecord_List { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyChangeRecord_List1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyOperation_List { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageMap_Get { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageMap_Get1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageMap_Get2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageMap_GetViaIdentity2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageMap_List { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageMap_List1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageMap_List2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageProgression_Get { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageProgression_Get1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageProgression_GetViaIdentity1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageProgression_List { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class GetAzChangeSafetyStageProgression_List1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    // endregion

    // region New
    public partial class NewAzChangeSafetyChangeRecord_CreateExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyChangeRecord_CreateExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyChangeRecord_CreateViaJsonFilePath { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyChangeRecord_CreateViaJsonFilePath1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyChangeRecord_CreateViaJsonString { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyChangeRecord_CreateViaJsonString1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateExpanded2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateViaJsonFilePath { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateViaJsonFilePath1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateViaJsonFilePath2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateViaJsonString { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateViaJsonString1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageMap_CreateViaJsonString2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageProgression_CreateExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageProgression_CreateExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageProgression_CreateViaJsonFilePath { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageProgression_CreateViaJsonFilePath1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageProgression_CreateViaJsonString { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class NewAzChangeSafetyStageProgression_CreateViaJsonString1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    // endregion

    // region Remove
    public partial class RemoveAzChangeSafetyChangeRecord_Delete { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyChangeRecord_Delete1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyChangeRecord_DeleteViaIdentity { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyChangeRecord_DeleteViaIdentity1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageMap_Delete { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageMap_Delete1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageMap_Delete2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageMap_DeleteViaIdentity { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageMap_DeleteViaIdentity1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageMap_DeleteViaIdentity2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageMap_DeleteViaIdentityManagementGroup { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageProgression_Delete { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageProgression_Delete1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageProgression_DeleteViaIdentity { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageProgression_DeleteViaIdentity1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageProgression_DeleteViaIdentityChangeRecord { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class RemoveAzChangeSafetyStageProgression_DeleteViaIdentityChangeRecord1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    // endregion

    // region Update
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateViaIdentityExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateViaIdentityExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateViaJsonFilePath { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateViaJsonFilePath1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateViaJsonString { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyChangeRecord_UpdateViaJsonString1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateExpanded2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaIdentityExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaIdentityExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaIdentityExpanded2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaIdentityManagementGroupExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaJsonFilePath { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaJsonFilePath1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaJsonFilePath2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaJsonString { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaJsonString1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageMap_UpdateViaJsonString2 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaIdentityChangeRecordExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaIdentityChangeRecordExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaIdentityExpanded { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaIdentityExpanded1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaJsonFilePath { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaJsonFilePath1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaJsonString { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    public partial class UpdateAzChangeSafetyStageProgression_UpdateViaJsonString1 { partial void overrideOnDefault(HttpResponseMessage responseMessage, Task<IErrorResponse> response, ref Task<bool> returnNow) { this.WriteError(responseMessage, response, ref returnNow); } }
    // endregion
}
