options:
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    emitter-output-dir: "{output-dir}/{service-dir}/Pinecone/Pinecone.Autorest"
    clear-output-folder: true
    azure: true
    module-version: 0.1.0
    prefix: "Az"
    subject-prefix: "Pinecone"
    service-name: Pinecone
    module-name: "{prefix}.{service-name}"
    output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type

    directive:
      # Following are common directives which are normally required in all the RPs
      # 1. Remove the unexpanded parameter set
      # 2. For New-* cmdlets, ViaIdentity is not required
      - where:
          variant: ^(Create|Update)(?!.*?(Expanded|JsonFilePath|JsonString))
        remove: true
      - where:
          variant: ^CreateViaIdentity.*$
        remove: true
      # Remove the Operation command
      - where:
          verb: Get
          subject: Operation
        remove: true
      # Read-only surface: remove all write cmdlets
      - where:
          verb: New
        remove: true
      - where:
          verb: Set
        remove: true
      - where:
          verb: Update
        remove: true
      - where:
          verb: Remove
        remove: true
      # Default SubscriptionId from the current context
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            name: SubscriptionId Default
            description: Gets the SubscriptionId from the current context.
            script: '(Get-AzContext).Subscription.Id'
