options:
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    emitter-output-dir: "{output-dir}/{service-dir}/FileShare/FileShare.Autorest"
    clear-output-folder: true
    debug: true
    azure: true
    module-version: 1.0.0
    prefix: "Az"
    subject-prefix: "FileShare"
    service-name: FileShare
    module-name: "{prefix}.{service-name}"
    output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: "(Get-AzContext).Subscription.Id"
      - where:
          variant: ^(Create|Update|Export)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          subject: MapConnection
          variant: ^(Get)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity$|^CreateViaIdentityExpanded$
        remove: true
      - where:
          verb: Set
        remove: true
      - where:
          parameter-name: NfProtocolPropertyEncryptionInTransitRequired
        set:
          parameter-name: EncryptionInTransitRequired
      - where:
          parameter-name: NfProtocolPropertyRootSquash
        set:
          parameter-name: RootSquash
      - where:
          parameter-name: PublicAccessPropertyAllowedSubnet
        set:
          parameter-name: AllowedSubnet
      - where:
          property-name: NfProtocolPropertyEncryptionInTransitRequired
        set:
          property-name: EncryptionInTransitRequired
      - where:
          property-name: NfProtocolPropertyRootSquash
        set:
          property-name: RootSquash
      - where:
          property-name: PublicAccessPropertyAllowedSubnet
        set:
          property-name: AllowedSubnet