
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Updates a existing streaming endpoint.
.Description
Updates a existing streaming endpoint.
.Example
{{ Add code here }}
.Example
{{ Add code here }}

.Inputs
Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Models.IMediaServicesIdentity
.Outputs
Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Models.Api20211101.IStreamingEndpoint
.Notes
COMPLEX PARAMETER PROPERTIES

To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.

AKAMAISIGNATUREHEADERAUTHENTICATIONKEYLIST <IAkamaiSignatureHeaderAuthenticationKey[]>: authentication key list
  [Base64Key <String>]: authentication key
  [Expiration <DateTime?>]: The expiration time of the authentication key.
  [Identifier <String>]: identifier of the key

INPUTOBJECT <IMediaServicesIdentity>: Identity Parameter
  [AccountName <String>]: The Media Services account name.
  [AssetName <String>]: The Asset name.
  [ContentKeyPolicyName <String>]: The Content Key Policy name.
  [FilterName <String>]: The Account Filter name
  [Id <String>]: Resource identity path
  [JobName <String>]: The Job name.
  [LiveEventName <String>]: The name of the live event, maximum length is 32.
  [LiveOutputName <String>]: The name of the live output.
  [LocationName <String>]: The name of the location
  [Name <String>]: 
  [OperationId <String>]: Operation Id.
  [ResourceGroupName <String>]: The name of the resource group within the Azure subscription.
  [StreamingEndpointName <String>]: The name of the streaming endpoint, maximum length is 24.
  [StreamingLocatorName <String>]: The Streaming Locator name.
  [StreamingPolicyName <String>]: The Streaming Policy name.
  [SubscriptionId <String>]: The unique identifier for a Microsoft Azure subscription.
  [TrackName <String>]: The Asset Track name.
  [TransformName <String>]: The Transform name.

IPALLOW <IIPRange[]>: The IP allow list.
  [Address <String>]: The IP address.
  [Name <String>]: The friendly name for the IP address range.
  [SubnetPrefixLength <Int32?>]: The subnet mask prefix length (see CIDR notation).
.Link
https://docs.microsoft.com/en-us/powershell/module/az.mediaservices/update-azmediaservicesstreamingendpoint
#>
function Update-AzMediaServicesStreamingEndpoint {
[OutputType([Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Models.Api20211101.IStreamingEndpoint])]
[CmdletBinding(DefaultParameterSetName='UpdateExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(ParameterSetName='UpdateExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Path')]
    [System.String]
    # The Media Services account name.
    ${AccountName},

    [Parameter(ParameterSetName='UpdateExpanded', Mandatory)]
    [Alias('StreamingEndpointName')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Path')]
    [System.String]
    # The name of the streaming endpoint, maximum length is 24.
    ${Name},

    [Parameter(ParameterSetName='UpdateExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Path')]
    [System.String]
    # The name of the resource group within the Azure subscription.
    ${ResourceGroupName},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Runtime.DefaultInfo(Script='(Get-AzContext).Subscription.Id')]
    [System.String]
    # The unique identifier for a Microsoft Azure subscription.
    ${SubscriptionId},

    [Parameter(ParameterSetName='UpdateViaIdentityExpanded', Mandatory, ValueFromPipeline)]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Models.IMediaServicesIdentity]
    # Identity Parameter
    # To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    ${InputObject},

    [Parameter(Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String]
    # The geo-location where the resource lives
    ${Location},

    [Parameter()]
    [AllowEmptyCollection()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Models.Api20211101.IAkamaiSignatureHeaderAuthenticationKey[]]
    # authentication key list
    # To construct, see NOTES section for AKAMAISIGNATUREHEADERAUTHENTICATIONKEYLIST properties and create a hash table.
    ${AkamaiSignatureHeaderAuthenticationKeyList},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String]
    # This feature is deprecated, do not set a value for this property.
    ${AvailabilitySetName},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # The CDN enabled flag.
    ${CdnEnabled},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String]
    # The CDN profile name.
    ${CdnProfile},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String]
    # The CDN provider name.
    ${CdnProvider},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String]
    # The content of clientaccesspolicy.xml used by Silverlight.
    ${CrossSiteAccessPolicyClientAccessPolicy},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String]
    # The content of crossdomain.xml used by Silverlight.
    ${CrossSiteAccessPolicyCrossDomainPolicy},

    [Parameter()]
    [AllowEmptyCollection()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String[]]
    # The custom host names of the streaming endpoint
    ${CustomHostName},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.String]
    # The streaming endpoint description.
    ${Description},

    [Parameter()]
    [AllowEmptyCollection()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Models.Api20211101.IIPRange[]]
    # The IP allow list.
    # To construct, see NOTES section for IPALLOW properties and create a hash table.
    ${IPAllow},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.Int64]
    # Max cache age
    ${MaxCacheAge},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.Int32]
    # The number of scale units.
    # Use the Scale operation to adjust this value.
    ${ScaleUnit},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [System.Int32]
    # The streaming endpoint sku capacity.
    ${SkuCapacity},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Runtime.Info(PossibleTypes=([Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Models.Api20.ITrackedResourceTags]))]
    [System.Collections.Hashtable]
    # Resource tags.
    ${Tag},

    [Parameter()]
    [Alias('AzureRMContext', 'AzureCredential')]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Azure')]
    [System.Management.Automation.PSObject]
    # The credentials, account, tenant, and subscription used for communication with Azure.
    ${DefaultProfile},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Run the command as a job
    ${AsJob},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Run the command asynchronously
    ${NoWait},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName

        if ($null -eq [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PowerShellVersion) {
            [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PowerShellVersion = $Host.Version.ToString()
        }         
        $preTelemetryId = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId
        if ($preTelemetryId -eq '') {
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId =(New-Guid).ToString()
            [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.module]::Instance.Telemetry.Invoke('Create', $MyInvocation, $parameterSet, $PSCmdlet)
        } else {
            $internalCalledCmdlets = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets
            if ($internalCalledCmdlets -eq '') {
                [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets = $MyInvocation.MyCommand.Name
            } else {
                [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets += ',' + $MyInvocation.MyCommand.Name
            }
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = 'internal'
        }

        $mapping = @{
            UpdateExpanded = 'Az.MediaServices.private\Update-AzMediaServicesStreamingEndpoint_UpdateExpanded';
            UpdateViaIdentityExpanded = 'Az.MediaServices.private\Update-AzMediaServicesStreamingEndpoint_UpdateViaIdentityExpanded';
        }
        if (('UpdateExpanded') -contains $parameterSet -and -not $PSBoundParameters.ContainsKey('SubscriptionId')) {
            $PSBoundParameters['SubscriptionId'] = (Get-AzContext).Subscription.Id
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }

    finally {
        $backupTelemetryId = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId
        $backupInternalCalledCmdlets = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
    }

}
end {
    try {
        $steppablePipeline.End()

        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = $backupTelemetryId
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets = $backupInternalCalledCmdlets
        if ($preTelemetryId -eq '') {
            [Microsoft.Azure.PowerShell.Cmdlets.MediaServices.module]::Instance.Telemetry.Invoke('Send', $MyInvocation, $parameterSet, $PSCmdlet)
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        }
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = $preTelemetryId

    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }
} 
}
