variables:
  BuildTimeoutInMinutes: 120

trigger: none

pr:
  branches:
    include:
      - '*'
    exclude:
      - Azs-tzl

jobs:
- job: Build
  displayName: Build
  condition: succeeded()
  timeoutInMinutes: ${{ variables.BuildTimeoutInMinutes }}
  pool: pool-windows-2019
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: 'Use .NET SDK for Build'
    inputs:
      packageType: sdk
      version: 8.x
  - task: NodeTool@0
    displayName: Install Autorest
    inputs:
      versionSpec: '18.20.7'
      command: custom
      verbose: false
      customCommand: install autorest@latest
  - task: PowerShell@2
    displayName: Setup environment for Autorest
    inputs:
      targetType: inline
      script: "$env:NODE_OPTIONS=\"--max-old-space-size=65536\""
      pwsh: true
  - task: Npm@1
    displayName: Install tsp client
    inputs:
      command: custom
      customCommand: install -g @azure-tools/typespec-client-generator-cli@0.15.x
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      targetType: inline
      pwsh: true
      script:
        Write-Host "POC pipeline triggered successfully!"

  - template: util/publish-artifacts-steps.yml
    parameters:
      artifactName: build-${{ variables.TestFramework }}

