# Variable 'BotAccessToken' was defined in the Variables tab
# Multi-job configuration must be converted to matrix strategy: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-job-configuration
parameters: []

jobs:
- job: Job_1
  displayName: "Sync latest UX metadata files to Storage Blob"
  timeoutInMinutes: 90
  pool: pool-windows-2019
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Compress the UX metadata files
    inputs:
      targetType: inline
      script: >-
        .\CompressUXMetadata.ps1
      workingDirectory: tools
  - task: AzurePowerShell@5
    displayName: Upload to Storage Blob
    inputs:
      targetType: inline
      script: >-
        $context = New-AzStorageContext -StorageAccountName "$(StorageAccountName)"
        Get-Item "artifacts/UX.zip" | Set-AzStorageBlobContent -Container $(StorageBlobContainerName) -Context $context -Force

