name: pr-labeled
run-name: Triggered by pr label
env:
  GH_TOKEN: ${{ github.token }}
  PR: ${{ github.event.pull_request.html_url }}
on:
  pull_request_target:
    types:
      - labeled
jobs:
  process_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
    - name: process label
      env:
        LABELNAME: ${{ github.event.label.name }}
      shell: pwsh
      run: .github/workflows/script/PrLabeled.ps1 -LabelName $env:LABELNAME -PrUrl $env:PR
