            - name: Single commit publish
  # You may pin to the exact commit or the version.
  # uses: antaljanosbenjamin/single-commit-publish@d736d043c821fc43c249724adaa5ac6bd577371d
  uses: antaljanosbenjamin/single-commit-publish@v1.0.1
  with:
    # GitHub token to use for push operation.
    github-token: 
    # GitHub username to use for push operation.
    github-actor: # optional, default is ${{ github.actor }}
    # The GitHub repository to where the files should be published in <username/repo> format.
    github-repository: # optional, default is ${{ github.repository }}
    # The branch to where the files should be published.
    branch: 
    # The source directory that contains all the files and directories that are going to be published. The directory structure inside this folder is going to be kept for the published files and directories.
    source-dir: # optional, default is ${{ github.workspace }}
    # List of paths (relative or absolute) of the files and directories to publish. They must be inside the source directory. The directory structure relative to source directory is kept for publishing.
    files-and-dirs: 
    # The name that will appear in the commit.
    author-name: # optional, default is github-actions
    # The email that will appear in the commit.
    author-email: # optional, default is github-actions@noreply.github.com
    # The commit message that will appear in the commit.
    commit-message: # optional, default is Publish from #${{ github.run_number }}
          
